# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Style Guide for Tests-Always-Included
email: tests-always-included@rumkin.com
baseurl: "/style-guide" # the subpath of your site, e.g. /blog or an empty string
# twitter_username: jekyllrb
github_username:  tests-always-included

######################################################################
# Site settings
######################################################################

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Style Guide
# this appears on the top navigation bar next to the home button

site_title: Tests-Always-Included Style Guide
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Tests-Always-Included
company_url: https://github.com/tests-always-included
# these appear in the footer

# github_editme_path: tests-always-included/style-guide/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# disqus_shortname: taistyleguide
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

# feedback_subject_line: TAI Style Guide

# feedback_email: tests-always-included@rumkin.com
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

# google_analytics: ""
# For enabling Google Analytics


######################################################################
# Feed Settings (feed.xml)
######################################################################

description: > # this means to ignore newlines until "baseurl:"
  A collection of style guides for various languages.  One guide to
  rule them all.
url: "http://example.com" # the base hostname & protocol for your site


######################################################################
# Build Settings
######################################################################

markdown: kramdown
kramdown:
    input: GFM
    auto_ids: true
    hard_wrap: false
    syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
            comments: true
            search: true
            sidebar: sidebar

# these are defaults used for the frontmatter for these file types

sidebars:
    - sidebar
